import fileinput
import lab1_python.source.analizator.AnalizatorBackBone as abb
from collections import defaultdict
from lab1_python.source.Util import Automate, Transition, Rule
fileinput_gen = fileinput.input()
rules_for_state = defaultdict(list)
rules_for_state['S_pocetno'].append(Rule(regex='\\t|\\_',uniform_sign='-',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\n',uniform_sign='-',udji_u_stanje=None,novi_redak=True,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='//',uniform_sign='-',udji_u_stanje='S_jednolinijskiKomentar',novi_redak=False,vrati_se=None,))
rules_for_state['S_jednolinijskiKomentar'].append(Rule(regex='\\n',uniform_sign='-',udji_u_stanje='S_pocetno',novi_redak=True,vrati_se=None,))
rules_for_state['S_jednolinijskiKomentar'].append(Rule(regex='(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\t|\\n|\\_|!|"|#|%|&|\'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)',uniform_sign='-',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='/\\*',uniform_sign='-',udji_u_stanje='S_komentar',novi_redak=False,vrati_se=None,))
rules_for_state['S_komentar'].append(Rule(regex='\\*/',uniform_sign='-',udji_u_stanje='S_pocetno',novi_redak=False,vrati_se=None,))
rules_for_state['S_komentar'].append(Rule(regex='\\n',uniform_sign='-',udji_u_stanje=None,novi_redak=True,vrati_se=None,))
rules_for_state['S_komentar'].append(Rule(regex='(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\t|\\n|\\_|!|"|#|%|&|\'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)',uniform_sign='-',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='"',uniform_sign='-',udji_u_stanje='S_string',novi_redak=False,vrati_se=0,))
rules_for_state['S_string'].append(Rule(regex='"((\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\t|\\_|!|#|%|&|\'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)|\\\\")*"',uniform_sign='NIZ_ZNAKOVA',udji_u_stanje='S_pocetno',novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='break',uniform_sign='KR_BREAK',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='char',uniform_sign='KR_CHAR',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='const',uniform_sign='KR_CONST',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='continue',uniform_sign='KR_CONTINUE',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='else',uniform_sign='KR_ELSE',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='for',uniform_sign='KR_FOR',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='if',uniform_sign='KR_IF',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='int',uniform_sign='KR_INT',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='return',uniform_sign='KR_RETURN',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='void',uniform_sign='KR_VOID',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='while',uniform_sign='KR_WHILE',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='(_|(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z))(_|(a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)|(0|1|2|3|4|5|6|7|8|9))*',uniform_sign='IDN',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='(0|1|2|3|4|5|6|7|8|9)(0|1|2|3|4|5|6|7|8|9)*',uniform_sign='BROJ',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='0(X|x)((0|1|2|3|4|5|6|7|8|9)|a|b|c|d|e|f|A|B|C|D|E|F)((0|1|2|3|4|5|6|7|8|9)|a|b|c|d|e|f|A|B|C|D|E|F)*',uniform_sign='BROJ',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\'(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\_|!|"|#|%|&|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)\'',uniform_sign='ZNAK',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\'\\\\(\\(|\\)|\\{|\\}|\\||\\*|\\\\|\\$|\\_|!|"|#|%|&|\'|+|,|-|.|/|0|1|2|3|4|5|6|7|8|9|:|;|<|=|>|?|@|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z|[|]|^|_|`|a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|~)\'',uniform_sign='ZNAK',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='++',uniform_sign='OP_INC',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='--',uniform_sign='OP_DEC',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='+',uniform_sign='PLUS',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='-',uniform_sign='MINUS',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\*',uniform_sign='OP_PUTA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='/',uniform_sign='OP_DIJELI',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='%',uniform_sign='OP_MOD',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='=',uniform_sign='OP_PRIDRUZI',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='<',uniform_sign='OP_LT',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='<=',uniform_sign='OP_LTE',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='>',uniform_sign='OP_GT',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='>=',uniform_sign='OP_GTE',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='==',uniform_sign='OP_EQ',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='!=',uniform_sign='OP_NEQ',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='!',uniform_sign='OP_NEG',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='~',uniform_sign='OP_TILDA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='&&',uniform_sign='OP_I',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\|\\|',uniform_sign='OP_ILI',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='&',uniform_sign='OP_BIN_I',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\|',uniform_sign='OP_BIN_ILI',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='^',uniform_sign='OP_BIN_XILI',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex=',',uniform_sign='ZAREZ',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex=';',uniform_sign='TOCKAZAREZ',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\(',uniform_sign='L_ZAGRADA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\)',uniform_sign='D_ZAGRADA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\{',uniform_sign='L_VIT_ZAGRADA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='\\}',uniform_sign='D_VIT_ZAGRADA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex='[',uniform_sign='L_UGL_ZAGRADA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
rules_for_state['S_pocetno'].append(Rule(regex=']',uniform_sign='D_UGL_ZAGRADA',udji_u_stanje=None,novi_redak=False,vrati_se=None,))
abb.parse_text(start_state='S_pocetno',rules_for_state=rules_for_state,fileinput_gen=fileinput_gen,file='qdcc')